sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: nkmyhinata.mysql.rds.aliyuncs.com
    port: 3306
    database: sky_take_out
    username: sky_take_out
    password: Hanser123$%^
